//go:build daemontest

package daemon

import (
	"bytes"
	"crypto/hmac"
	"crypto/sha256"
	"crypto/tls"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"net/http/cookiejar"
	"os"
	"strconv"
	"strings"
	"testing"
	"time"

	"golang.org/x/crypto/ssh"
)

// Global test state — populated by TestMain.
var (
	daemonURL     string // e.g. https://daemon-test-api:8443
	daemonHTTPURL string // e.g. http://daemon-test-api:8080
	daemonPort9001 string // e.g. https://daemon-test-api:9001
	appURL        string // e.g. http://test-server-api:3000
	testSecret    string
	machineID     string
	machineToken  string // HMAC heartbeat secret (hex-encoded)

	managedMachineID string // auto-generated by create-machine
	appMachineID     string // the machine.id in the app DB (different from daemon's IDAPT_MACHINE_ID)
	machineSlug      string // auto-generated slug for the test machine

	// Test user credentials
	testUserEmail   string
	testUserAuth    string // cookie header
	testUserActorID string
	testProjectID   string

)

func TestMain(m *testing.M) {
	daemonURL = envOrFatal("DAEMON_TEST_URL")
	daemonHTTPURL = envOrFatal("DAEMON_HTTP_URL")
	daemonPort9001 = os.Getenv("DAEMON_PORT_9001_URL")
	if daemonPort9001 == "" {
		daemonPort9001 = strings.Replace(daemonURL, ":8443", ":9001", 1)
	}
	appURL = envOrFatal("APP_TEST_URL")
	testSecret = envOrFatal("TEST_SECRET")
	machineID = envOrFatal("DAEMON_MACHINE_ID")

	// Wait for daemon to be healthy
	if err := waitForDaemonHealthy(60 * time.Second); err != nil {
		log.Fatalf("Daemon not healthy: %v", err)
	}
	log.Println("Daemon is healthy")

	// Create test user via app
	if err := createTestUser(); err != nil {
		log.Fatalf("Failed to create test user: %v", err)
	}
	log.Printf("Test user created: %s (actor: %s)", testUserEmail, testUserActorID)

	// Create managed machine record in app (gets auto-generated IDs)
	if err := createTestMachine(); err != nil {
		log.Printf("WARN: Could not create test machine (some tests may skip): %v", err)
	} else {
		log.Printf("Test machine created: machineId=%s managedMachineId=%s slug=%s", appMachineID, managedMachineID, machineSlug)
		// Update daemon's JWT validator to accept the managedMachineId
		// (the auth endpoint uses managedMachineId as JWT "mid" claim)
		if err := setDaemonMachineID(managedMachineID); err != nil {
			log.Printf("WARN: Could not set daemon machine ID: %v", err)
		}
	}

	// Fetch heartbeat secret from app
	if err := fetchHeartbeatSecret(); err != nil {
		log.Printf("WARN: Could not fetch heartbeat secret: %v", err)
	} else {
		log.Println("Heartbeat secret fetched")
	}

	os.Exit(m.Run())
}

// --- HTTP helpers ---

// daemonClient returns an HTTP client that skips TLS verification and does NOT follow redirects.
func daemonClient() *http.Client {
	return &http.Client{
		Transport: &http.Transport{
			TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
		},
		CheckRedirect: func(req *http.Request, via []*http.Request) error {
			return http.ErrUseLastResponse // don't follow redirects
		},
		Timeout: 30 * time.Second,
	}
}

// daemonClientWithCookies returns a client that handles cookies (for auth flow testing).
func daemonClientWithCookies() *http.Client {
	jar, _ := cookiejar.New(nil)
	return &http.Client{
		Transport: &http.Transport{
			TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
		},
		Jar:     jar,
		Timeout: 30 * time.Second,
		CheckRedirect: func(req *http.Request, via []*http.Request) error {
			return http.ErrUseLastResponse
		},
	}
}

type requestOption func(*http.Request)

func withCookie(name, value string) requestOption {
	return func(r *http.Request) {
		r.AddCookie(&http.Cookie{Name: name, Value: value})
	}
}

func withHeader(key, value string) requestOption {
	return func(r *http.Request) {
		r.Header.Set(key, value)
	}
}

func withBearer(token string) requestOption {
	return withHeader("Authorization", "Bearer "+token)
}

func withJSON(body interface{}) requestOption {
	return func(r *http.Request) {
		data, _ := json.Marshal(body)
		r.Body = io.NopCloser(bytes.NewReader(data))
		r.ContentLength = int64(len(data))
		r.Header.Set("Content-Type", "application/json")
	}
}

// daemonRequest makes an HTTPS request to the daemon on the default port.
func daemonRequest(t *testing.T, method, path string, opts ...requestOption) *http.Response {
	t.Helper()
	return doRequest(t, daemonURL+path, method, opts...)
}

// daemonRequestPort makes an HTTPS request to the daemon on a specific port.
func daemonRequestPort(t *testing.T, baseURL, method, path string, opts ...requestOption) *http.Response {
	t.Helper()
	return doRequest(t, baseURL+path, method, opts...)
}

// daemonHTTPRequest makes an HTTP (not HTTPS) request to the daemon.
func daemonHTTPRequest(t *testing.T, method, path string, opts ...requestOption) *http.Response {
	t.Helper()
	return doRequest(t, daemonHTTPURL+path, method, opts...)
}

// appRequest makes a request to the app server.
func appRequest(t *testing.T, method, path string, opts ...requestOption) *http.Response {
	t.Helper()
	return doRequest(t, appURL+path, method, opts...)
}

func doRequest(t *testing.T, url, method string, opts ...requestOption) *http.Response {
	t.Helper()
	req, err := http.NewRequest(method, url, nil)
	if err != nil {
		t.Fatalf("Failed to create request: %v", err)
	}
	for _, opt := range opts {
		opt(req)
	}
	resp, err := daemonClient().Do(req)
	if err != nil {
		t.Fatalf("Request failed: %v", err)
	}
	return resp
}

func readBody(t *testing.T, resp *http.Response) string {
	t.Helper()
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		t.Fatalf("Failed to read body: %v", err)
	}
	return string(body)
}

func readJSON(t *testing.T, resp *http.Response) map[string]interface{} {
	t.Helper()
	body := readBody(t, resp)
	var result map[string]interface{}
	if err := json.Unmarshal([]byte(body), &result); err != nil {
		t.Fatalf("Failed to parse JSON: %v\nBody: %s", err, body)
	}
	return result
}

// --- HMAC helpers ---

// computeHMAC computes HMAC-SHA256 for daemon management APIs.
// Format: METHOD:PATH:TIMESTAMP
// The daemon hex-decodes the machineToken before using it as HMAC key,
// so we must do the same here (the app returns it as hex-encoded bytes).
func computeHMAC(method, path, timestamp, secret string) string {
	message := fmt.Sprintf("%s:%s:%s", method, path, timestamp)
	keyBytes, err := hex.DecodeString(secret)
	if err != nil {
		keyBytes = []byte(secret) // fallback: raw bytes if not valid hex
	}
	mac := hmac.New(sha256.New, keyBytes)
	mac.Write([]byte(message))
	return hex.EncodeToString(mac.Sum(nil))
}

func withHMAC(method, path, secret string) []requestOption {
	timestamp := strconv.FormatInt(time.Now().Unix(), 10)
	sig := computeHMAC(method, path, timestamp, secret)
	return []requestOption{
		withHeader("X-Machine-Signature", sig),
		withHeader("X-Machine-Timestamp", timestamp),
	}
}

// --- JWT helpers ---

// issueJWTViaApp calls the app's auth endpoint and extracts the JWT from the redirect URL.
func issueJWTViaApp(t *testing.T, path string) string {
	t.Helper()

	if machineSlug == "" {
		t.Skip("No machine slug available — machine creation may have failed")
	}

	// Ensure daemon's JWT validator accepts this machine's managedMachineId
	// (may have been reset by a restart test — the auth endpoint uses managedMachineId as JWT "mid")
	if managedMachineID != "" {
		if err := setDaemonMachineID(managedMachineID); err != nil {
			t.Logf("WARN: Could not set daemon machine ID: %v", err)
		}
	}

	// Call the app's machine auth endpoint with session cookie
	req, err := http.NewRequest("GET", fmt.Sprintf("%s/api/managed-machines/auth?slug=%s&path=%s", appURL, machineSlug, path), nil)
	if err != nil {
		t.Fatalf("Failed to create auth request: %v", err)
	}
	req.Header.Set("Cookie", testUserAuth)
	req.Header.Set("Origin", appURL)

	client := &http.Client{
		CheckRedirect: func(req *http.Request, via []*http.Request) error {
			return http.ErrUseLastResponse
		},
		Timeout: 10 * time.Second,
	}
	resp, err := client.Do(req)
	if err != nil {
		t.Fatalf("Auth request failed: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusFound && resp.StatusCode != http.StatusTemporaryRedirect {
		body, _ := io.ReadAll(resp.Body)
		t.Fatalf("Expected redirect from auth endpoint, got %d: %s", resp.StatusCode, string(body))
	}

	// Extract token from redirect URL: https://{slug}.localhost:PORT/__auth_callback?token=JWT&path=/...
	location := resp.Header.Get("Location")
	if location == "" {
		t.Fatal("No Location header in auth redirect")
	}
	t.Logf("Auth redirect Location: %s", location[:min(len(location), 120)])

	// Parse token from URL
	parts := strings.Split(location, "token=")
	if len(parts) < 2 {
		t.Fatalf("No token in redirect URL: %s", location)
	}
	token := parts[1]
	if idx := strings.Index(token, "&"); idx != -1 {
		token = token[:idx]
	}

	t.Logf("Extracted JWT (first 50 chars): %s...", token[:min(len(token), 50)])
	return token
}

// --- SSH helpers ---

func sshExec(t *testing.T, command string) (string, error) {
	t.Helper()
	host := os.Getenv("SSH_TEST_HOST")
	port := os.Getenv("SSH_TEST_PORT")
	user := os.Getenv("SSH_TEST_USER")
	password := os.Getenv("SSH_TEST_PASSWORD")

	if host == "" || port == "" {
		t.Skip("SSH_TEST_HOST/SSH_TEST_PORT not set, skipping SSH test")
	}

	config := &ssh.ClientConfig{
		User: user,
		Auth: []ssh.AuthMethod{
			ssh.Password(password),
		},
		HostKeyCallback: ssh.InsecureIgnoreHostKey(),
		Timeout:         10 * time.Second,
	}

	client, err := ssh.Dial("tcp", host+":"+port, config)
	if err != nil {
		return "", fmt.Errorf("SSH dial: %w", err)
	}
	defer client.Close()

	session, err := client.NewSession()
	if err != nil {
		return "", fmt.Errorf("SSH session: %w", err)
	}
	defer session.Close()

	out, err := session.CombinedOutput(command)
	return string(out), err
}

// --- Daemon test management helpers ---

// daemonExec runs a command inside the daemon container via /__test/exec.
func daemonExec(t *testing.T, command string) (string, string) {
	t.Helper()
	resp := daemonRequest(t, "POST", "/__test/exec",
		withJSON(map[string]string{"command": command}))
	result := readJSON(t, resp)
	output, _ := result["output"].(string)
	errStr, _ := result["error"].(string)
	return output, errStr
}

// triggerDaemonRestart sends SIGUSR1 to the daemon via /__test/signal/restart.
func triggerDaemonRestart(t *testing.T) {
	t.Helper()
	resp := daemonRequest(t, "POST", "/__test/signal/restart")
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("Restart trigger failed: %d", resp.StatusCode)
	}
	resp.Body.Close()
}

// setDaemonMachineID updates the daemon's JWT validator to accept the given machineId.
func setDaemonMachineID(newMachineID string) error {
	body, _ := json.Marshal(map[string]string{"machineId": newMachineID})
	req, _ := http.NewRequest("POST", daemonURL+"/__test/set-machine-id", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	client := &http.Client{
		Transport: &http.Transport{
			TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
		},
		Timeout: 10 * time.Second,
	}
	resp, err := client.Do(req)
	if err != nil {
		return err
	}
	resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("set-machine-id returned %d", resp.StatusCode)
	}
	return nil
}

// blockApp toggles app connectivity via /__test/block-app.
func blockApp(t *testing.T, block bool) {
	t.Helper()
	resp := daemonRequest(t, "POST", "/__test/block-app",
		withJSON(map[string]bool{"block": block}))
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("Block app failed: %d", resp.StatusCode)
	}
	resp.Body.Close()
}

// waitForDaemonHealthy polls the daemon health endpoint until success or timeout.
func waitForDaemonHealthy(timeout time.Duration) error {
	deadline := time.Now().Add(timeout)
	client := daemonClient()
	for time.Now().Before(deadline) {
		req, _ := http.NewRequest("GET", daemonURL+"/api/health", nil)
		resp, err := client.Do(req)
		if err == nil {
			resp.Body.Close()
			if resp.StatusCode == http.StatusOK {
				return nil
			}
		}
		time.Sleep(1 * time.Second)
	}
	return fmt.Errorf("daemon not healthy after %v", timeout)
}

// --- App setup helpers ---

func envOrFatal(key string) string {
	v := os.Getenv(key)
	if v == "" {
		log.Fatalf("Required env var %s not set", key)
	}
	return v
}

func createTestUser() error {
	testUserEmail = fmt.Sprintf("test-daemon-%d@test.idapt.ai", time.Now().UnixNano())

	body, _ := json.Marshal(map[string]interface{}{
		"users": []map[string]string{
			{"email": testUserEmail, "password": "TestPassword123!@#", "name": "Daemon Test User"},
		},
	})

	req, _ := http.NewRequest("POST", appURL+"/api/admin/test/create-users", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("x-test-secret", testSecret)
	req.Header.Set("Origin", appURL)

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return fmt.Errorf("create user: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		respBody, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("create user returned %d: %s", resp.StatusCode, string(respBody))
	}

	var rawResp map[string]interface{}
	respBody, _ := io.ReadAll(resp.Body)
	if err := json.Unmarshal(respBody, &rawResp); err != nil {
		return fmt.Errorf("parse create user response: %w (body: %s)", err, string(respBody))
	}

	users, ok := rawResp["users"].([]interface{})
	if !ok || len(users) == 0 {
		return fmt.Errorf("no users in response: %s", string(respBody))
	}
	user0, _ := users[0].(map[string]interface{})
	testUserActorID, _ = user0["actorId"].(string)
	sessionToken, _ := user0["sessionToken"].(string)
	if testUserActorID == "" {
		return fmt.Errorf("no actorId in response: %s", string(respBody))
	}

	// Build cookie header from session token
	if sessionToken != "" {
		testUserAuth = "better-auth.session_token=" + sessionToken
	} else {
		return fmt.Errorf("no sessionToken in response: %s", string(respBody))
	}

	// Get personal project
	req2, _ := http.NewRequest("GET", appURL+"/api/projects", nil)
	req2.Header.Set("Cookie", testUserAuth)
	req2.Header.Set("Origin", appURL)
	resp2, err := http.DefaultClient.Do(req2)
	if err != nil {
		return fmt.Errorf("get projects: %w", err)
	}
	defer resp2.Body.Close()

	var projectsResp struct {
		Projects []map[string]interface{} `json:"projects"`
	}
	json.NewDecoder(resp2.Body).Decode(&projectsResp)
	for _, p := range projectsResp.Projects {
		if p["isPersonal"] == true {
			testProjectID, _ = p["id"].(string)
			break
		}
	}
	if testProjectID == "" {
		return fmt.Errorf("no personal project found")
	}

	// Grant max subscription for machine features
	grantBody, _ := json.Marshal(map[string]string{
		"email": testUserEmail, "tier": "max",
	})
	req3, _ := http.NewRequest("POST", appURL+"/api/admin/test/grant-subscription", bytes.NewReader(grantBody))
	req3.Header.Set("Content-Type", "application/json")
	req3.Header.Set("x-test-secret", testSecret)
	req3.Header.Set("Origin", appURL)
	resp3, _ := http.DefaultClient.Do(req3)
	if resp3 != nil {
		resp3.Body.Close()
	}

	return nil
}

func createTestMachine() error {
	body, _ := json.Marshal(map[string]interface{}{
		"action":    "create-machine",
		"projectId": testProjectID,
		"actorId":   testUserActorID,
		"baseImage": "ubuntu-24.04",
	})

	req, _ := http.NewRequest("POST", appURL+"/api/admin/test/managed-machine-state", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("x-test-secret", testSecret)
	req.Header.Set("Origin", appURL)

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return fmt.Errorf("create machine: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK && resp.StatusCode != http.StatusCreated {
		respBody, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("create machine returned %d: %s", resp.StatusCode, string(respBody))
	}

	// Parse response to get auto-generated IDs
	var createResp struct {
		ManagedMachine struct {
			ID        string `json:"id"`
			MachineID string `json:"machineId"`
			Slug      string `json:"slug"`
		} `json:"managedMachine"`
	}
	respBody2, _ := io.ReadAll(resp.Body)
	if err := json.Unmarshal(respBody2, &createResp); err != nil {
		return fmt.Errorf("parse create machine response: %w (body: %s)", err, string(respBody2))
	}
	managedMachineID = createResp.ManagedMachine.ID
	appMachineID = createResp.ManagedMachine.MachineID
	machineSlug = createResp.ManagedMachine.Slug
	log.Printf("Machine created: managedMachineId=%s, machineId=%s, slug=%s", managedMachineID, appMachineID, machineSlug)

	// Force to running state
	stateBody, _ := json.Marshal(map[string]interface{}{
		"action":           "set-state",
		"managedMachineId": managedMachineID,
		"state":            "running",
	})

	req2, _ := http.NewRequest("POST", appURL+"/api/admin/test/managed-machine-state", bytes.NewReader(stateBody))
	req2.Header.Set("Content-Type", "application/json")
	req2.Header.Set("x-test-secret", testSecret)
	req2.Header.Set("Origin", appURL)

	resp2, err := http.DefaultClient.Do(req2)
	if err != nil {
		return fmt.Errorf("set state: %w", err)
	}
	resp2.Body.Close()

	return nil
}

func fetchHeartbeatSecret() error {
	req, _ := http.NewRequest("GET", fmt.Sprintf("%s/api/admin/test/machine-heartbeat-secret?machineId=%s", appURL, machineID), nil)
	req.Header.Set("x-test-secret", testSecret)
	req.Header.Set("Origin", appURL)

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	var result struct {
		Secret string `json:"secret"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return err
	}
	machineToken = result.Secret
	return nil
}

